allowBuilds:
  'esbuild': true
  'sharp': true
  'unrs-resolver': true

minimumReleaseAgeExclude:
  - '@linteljs/*'

peerDependencyRules:
  allowedVersions:
    'eslint-plugin-import>eslint': '10'
    'eslint-plugin-jsx-a11y>eslint': '10'
